version: "3.9"
services:
  server:
    image: app
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"